//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtopakSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategori
    {
        public int Kategori_ID { get; set; }
        public string Kategori_AD { get; set; }
        public Nullable<int> KatID { get; set; }
    
        public virtual Katlar Katlar { get; set; }
    }
}
