//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtopakSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcı
    {
        public int Kullanıcı_ID { get; set; }
        public string Adı { get; set; }
        public string Soyadı { get; set; }
        public Nullable<int> Tel { get; set; }
        public string E_mail { get; set; }
        public string Arac_plaka { get; set; }
        public Nullable<int> Sifre { get; set; }
    }
}
