//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtopakSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Park_Yeri
    {
        public int P_Yeri_ID { get; set; }
        public string Durumu { get; set; }
        public Nullable<int> A_Kapı_uzaklığı { get; set; }
        public Nullable<int> B_Kapı_uzaklığı { get; set; }
        public Nullable<int> KatID { get; set; }
    
        public virtual Katlar Katlar { get; set; }
    }
}
